CREATE TABLE Sensor
(
    name varchar PRIMARY KEY
);

CREATE TABLE Measurement
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value       double precision NOT NULL CHECK (value BETWEEN -100.0 AND 100.0),
    raining     bool             NOT NULL,
    date_time   timestamp DEFAULT NOW(),
    sensor_name varchar          NOT NULL REFERENCES sensor (name) ON DELETE CASCADE
);